DROP TABLE IF EXISTS ComponentMessageHistory;

CREATE TABLE ComponentMessageHistory (
  Id BIGINT GENERATED BY DEFAULT AS IDENTITY,
  ComponentName VARCHAR(255) NOT NULL,
  StartTime BIGINT NOT NULL,
  EndTime BIGINT,
  MessageHistoryId BIGINT,
  ComponentIndex INTEGER,
  PRIMARY KEY (Id));

ALTER TABLE ComponentMessageHistory ADD CONSTRAINT
  ComponentMessageHistory_Id_FK FOREIGN KEY (MessageHistoryId) REFERENCES MessageHistory ON DELETE CASCADE;