package org.ikasan.component.endpoint.kafka.client.reactive.consumer;

import org.apache.kafka.clients.CommonClientConfigs;
import org.apache.kafka.clients.consumer.ConsumerConfig;
import org.apache.kafka.common.config.SaslConfigs;
import org.apache.kafka.common.config.SslConfigs;
import org.apache.kafka.common.serialization.StringDeserializer;
import org.junit.Assert;
import org.junit.Test;

import java.util.Arrays;
import java.util.Map;

public class KafkaConsumerConfigurationTest {

    @Test
    public void test_getConsumerProps() throws ClassNotFoundException {
        KafkaConsumerConfiguration config = new KafkaConsumerConfiguration();

        // Set all properties
        config.setKeyDeserializer(StringDeserializer.class.getName());
        config.setValueDeserializer(StringDeserializer.class.getName());
        config.setBootstrapServers(Arrays.asList("localhost:9092"));
        config.setFetchMinBytes(1);
        config.setGroupId("test-group");
        config.setHeartbeatIntervalMillis(3000);
        config.setMaxPartitionFetchBytes(1048576);
        config.setSessionTimeoutMillis(10000);
        config.setSslKeyPassword("key_password");
        config.setSslKeystoreLocation("/keystore.jks");
        config.setSslKeystorePassword("keystore_password");
        config.setSslTruststoreLocation("/truststore.jks");
        config.setSslTruststorePassword("truststore_password");
        config.setAllowAutoCreateTopics(false);
        config.setAutoOffsetReset("earliest");
        config.setClientDnsLookup("use_all_dns_ips");
        config.setConnectionsMaxIdleMillis(540000L);
        config.setDefaultApiTimeoutMillis(60000L);
        config.setEnableAutoCommit(false);
        config.setExcludeInternalTopics(false);
        config.setFetchMaxBytes(52428800);
        config.setGroupInstanceId("group-instance-1");
        config.setIsolationLevel("read_committed");
        config.setMaxPollIntervalMillis(300000L);
        config.setMaxPollRecords(500);
        config.setPartitionAssignmentStrategy(Arrays.asList("org.apache.kafka.clients.consumer.RoundRobinAssignor"));
        config.setReceiveBufferBytes(65536);
        config.setRequestTimeoutMillis(30000L);
        config.setSaslClientCallbackHandlerClass("com.example.MySaslClientCallbackHandler");
        config.setSaslJaasConfig("jaas_config");
        config.setSaslKerberosServiceName("kafka");
        config.setSaslLoginCallbackHandlerClass("com.example.MySaslLoginCallbackHandler");
        config.setSaslLoginClass("com.example.MySaslLogin");
        config.setSaslMechanism("GSSAPI");
        config.setSecurityProtocol("SASL_SSL");
        config.setSendBufferBytes(131072);
        config.setSslEnabledProtocols(Arrays.asList("TLSv1.2", "TLSv1.3"));
        config.setSslKeystoreType("JKS");
        config.setSslProtocol("TLSv1.2");
        config.setSslProvider("SUN");
        config.setSslTruststoreType("JKS");
        config.setAutoCommitIntervalMillis(5000);
        config.setCheckCrcs(true);
        config.setClientId("client-1");
        config.setClientRack("rack-1");
        config.setFetchMaxWaitMillis(500L);
        config.setInterceptorClasses(Arrays.asList("com.example.MyInterceptor"));
        config.setMetadataMaxAgeMillis(300000L);
        config.setMetricReporters(Arrays.asList("com.example.MyMetricsReporter"));
        config.setMetricsNumSamples(2);
        config.setMetricsRecordingLevel("INFO");
        config.setMetricsSampleWindowMillis(30000L);
        config.setReconnectBackoffMaxMillis(1000L);
        config.setReconnectBackoffMillis(50L);
        config.setRetryBackoffMillis(100L);
        config.setSaslKerberosKinitCmd("/usr/bin/kinit");
        config.setSaslKerberosMinTimeBeforeRelogin(60000L);
        config.setSaslKerberosTicketRenewJitter("0.05");
        config.setSaslKerberosTicketRenewWindowFactor("0.8");
        config.setSaslLoginRefreshBufferSeconds(300);
        config.setSaslLoginRefreshMinPeriodSeconds(60);
        config.setSaslLoginRefreshWindowFactor("0.8");
        config.setSaslLoginRefreshWindowJitter("0.05");
        config.setSecurityProviders("com.example.MySecurityProvider");
        config.setSslCipherSuites(Arrays.asList("TLS_RSA_WITH_AES_256_CBC_SHA"));
        config.setSslEndpointIdentificationAlgorithm("https");
        config.setSslEngineFactoryClass("com.example.MySslEngineFactory");
        config.setSslKeymanagerAlgorithm("SunX509");
        config.setSslSecureRandomImplementation("SHA1PRNG");
        config.setSslTrustmanagerAlgorithm("PKIX");

        Map<String, Object> props = config.getConsumerProps();

        Assert.assertEquals(Class.forName(StringDeserializer.class.getName()), props.get(ConsumerConfig.KEY_DESERIALIZER_CLASS_CONFIG));
        Assert.assertEquals(Class.forName(StringDeserializer.class.getName()), props.get(ConsumerConfig.VALUE_DESERIALIZER_CLASS_CONFIG));
        Assert.assertEquals(Arrays.asList("localhost:9092"), props.get(ConsumerConfig.BOOTSTRAP_SERVERS_CONFIG));
        Assert.assertEquals(1, props.get(ConsumerConfig.FETCH_MIN_BYTES_CONFIG));
        Assert.assertEquals("test-group", props.get(ConsumerConfig.GROUP_ID_CONFIG));
        Assert.assertEquals(3000, props.get(ConsumerConfig.HEARTBEAT_INTERVAL_MS_CONFIG));
        Assert.assertEquals(1048576, props.get(ConsumerConfig.MAX_PARTITION_FETCH_BYTES_CONFIG));
        Assert.assertEquals(10000, props.get(ConsumerConfig.SESSION_TIMEOUT_MS_CONFIG));
        Assert.assertEquals("key_password", props.get(SslConfigs.SSL_KEY_PASSWORD_CONFIG));
        Assert.assertEquals("/keystore.jks", props.get(SslConfigs.SSL_KEYSTORE_LOCATION_CONFIG));
        Assert.assertEquals("keystore_password", props.get(SslConfigs.SSL_KEYSTORE_PASSWORD_CONFIG));
        Assert.assertEquals("/truststore.jks", props.get(SslConfigs.SSL_TRUSTSTORE_LOCATION_CONFIG));
        Assert.assertEquals("truststore_password", props.get(SslConfigs.SSL_TRUSTSTORE_PASSWORD_CONFIG));
        Assert.assertEquals(false, props.get(ConsumerConfig.ALLOW_AUTO_CREATE_TOPICS_CONFIG));
        Assert.assertEquals("earliest", props.get(ConsumerConfig.AUTO_OFFSET_RESET_CONFIG));
        Assert.assertEquals("use_all_dns_ips", props.get(ConsumerConfig.CLIENT_DNS_LOOKUP_CONFIG));
        Assert.assertEquals(540000L, props.get(ConsumerConfig.CONNECTIONS_MAX_IDLE_MS_CONFIG));
        Assert.assertEquals(60000L, props.get(ConsumerConfig.DEFAULT_API_TIMEOUT_MS_CONFIG));
        Assert.assertEquals(false, props.get(ConsumerConfig.ENABLE_AUTO_COMMIT_CONFIG));
        Assert.assertEquals(false, props.get(ConsumerConfig.EXCLUDE_INTERNAL_TOPICS_CONFIG));
        Assert.assertEquals(52428800, props.get(ConsumerConfig.FETCH_MAX_BYTES_CONFIG));
        Assert.assertEquals("group-instance-1", props.get(ConsumerConfig.GROUP_INSTANCE_ID_CONFIG));
        Assert.assertEquals("read_committed", props.get(ConsumerConfig.ISOLATION_LEVEL_CONFIG));
        Assert.assertEquals(300000L, props.get(ConsumerConfig.MAX_POLL_INTERVAL_MS_CONFIG));
        Assert.assertEquals(500, props.get(ConsumerConfig.MAX_POLL_RECORDS_CONFIG));
        Assert.assertEquals(Arrays.asList("org.apache.kafka.clients.consumer.RoundRobinAssignor"), props.get(ConsumerConfig.PARTITION_ASSIGNMENT_STRATEGY_CONFIG));
        Assert.assertEquals(65536, props.get(ConsumerConfig.RECEIVE_BUFFER_CONFIG));
        Assert.assertEquals(30000L, props.get(ConsumerConfig.REQUEST_TIMEOUT_MS_CONFIG));
        Assert.assertEquals("com.example.MySaslClientCallbackHandler", props.get(SaslConfigs.SASL_CLIENT_CALLBACK_HANDLER_CLASS));
        Assert.assertEquals("jaas_config", props.get(SaslConfigs.SASL_JAAS_CONFIG));
        Assert.assertEquals("kafka", props.get(SaslConfigs.SASL_KERBEROS_SERVICE_NAME));
        Assert.assertEquals("com.example.MySaslLoginCallbackHandler", props.get(SaslConfigs.SASL_LOGIN_CALLBACK_HANDLER_CLASS));
        Assert.assertEquals("com.example.MySaslLogin", props.get(SaslConfigs.SASL_LOGIN_CLASS));
        Assert.assertEquals("GSSAPI", props.get(SaslConfigs.SASL_MECHANISM));
        Assert.assertEquals("SASL_SSL", props.get(CommonClientConfigs.SECURITY_PROTOCOL_CONFIG));
        Assert.assertEquals(131072, props.get(ConsumerConfig.SEND_BUFFER_CONFIG));
        Assert.assertEquals(Arrays.asList("TLSv1.2", "TLSv1.3"), props.get(SslConfigs.SSL_ENABLED_PROTOCOLS_CONFIG));
        Assert.assertEquals("JKS", props.get(SslConfigs.SSL_KEYSTORE_TYPE_CONFIG));
        Assert.assertEquals("TLSv1.2", props.get(SslConfigs.SSL_PROTOCOL_CONFIG));
        Assert.assertEquals("SUN", props.get(SslConfigs.SSL_PROVIDER_CONFIG));
        Assert.assertEquals("JKS", props.get(SslConfigs.SSL_TRUSTSTORE_TYPE_CONFIG));
        Assert.assertEquals(5000, props.get(ConsumerConfig.AUTO_COMMIT_INTERVAL_MS_CONFIG));
        Assert.assertEquals(true, props.get(ConsumerConfig.CHECK_CRCS_CONFIG));
        Assert.assertEquals("client-1", props.get(ConsumerConfig.CLIENT_ID_CONFIG));
        Assert.assertEquals("rack-1", props.get(ConsumerConfig.CLIENT_RACK_CONFIG));
        Assert.assertEquals(500L, props.get(ConsumerConfig.FETCH_MAX_WAIT_MS_CONFIG));
        Assert.assertEquals(Arrays.asList("com.example.MyInterceptor"), props.get(ConsumerConfig.INTERCEPTOR_CLASSES_CONFIG));
        Assert.assertEquals(300000L, props.get(ConsumerConfig.METADATA_MAX_AGE_CONFIG));
        Assert.assertEquals(Arrays.asList("com.example.MyMetricsReporter"), props.get(ConsumerConfig.METRIC_REPORTER_CLASSES_CONFIG));
        Assert.assertEquals(2, props.get(ConsumerConfig.METRICS_NUM_SAMPLES_CONFIG));
        Assert.assertEquals("INFO", props.get(ConsumerConfig.METRICS_RECORDING_LEVEL_CONFIG));
        Assert.assertEquals(30000L, props.get(ConsumerConfig.METRICS_SAMPLE_WINDOW_MS_CONFIG));
        Assert.assertEquals(1000L, props.get(ConsumerConfig.RECONNECT_BACKOFF_MAX_MS_CONFIG));
        Assert.assertEquals(50L, props.get(ConsumerConfig.RECONNECT_BACKOFF_MS_CONFIG));
        Assert.assertEquals(100L, props.get(ConsumerConfig.RETRY_BACKOFF_MS_CONFIG));
        Assert.assertEquals("/usr/bin/kinit", props.get(SaslConfigs.SASL_KERBEROS_KINIT_CMD));
        Assert.assertEquals(60000L, props.get(SaslConfigs.SASL_KERBEROS_MIN_TIME_BEFORE_RELOGIN));
        Assert.assertEquals("0.05", props.get(SaslConfigs.SASL_KERBEROS_TICKET_RENEW_JITTER));
        Assert.assertEquals("0.8", props.get(SaslConfigs.SASL_KERBEROS_TICKET_RENEW_WINDOW_FACTOR));
        Assert.assertEquals(300, props.get(SaslConfigs.SASL_LOGIN_REFRESH_BUFFER_SECONDS));
        Assert.assertEquals(60, props.get(SaslConfigs.SASL_LOGIN_REFRESH_MIN_PERIOD_SECONDS));
        Assert.assertEquals("0.8", props.get(SaslConfigs.SASL_LOGIN_REFRESH_WINDOW_FACTOR));
        Assert.assertEquals("0.05", props.get(SaslConfigs.SASL_LOGIN_REFRESH_WINDOW_JITTER));
        Assert.assertEquals("com.example.MySecurityProvider", props.get(ConsumerConfig.SECURITY_PROVIDERS_CONFIG));
        Assert.assertEquals(Arrays.asList("TLS_RSA_WITH_AES_256_CBC_SHA"), props.get(SslConfigs.SSL_CIPHER_SUITES_CONFIG));
        Assert.assertEquals("https", props.get(SslConfigs.SSL_ENDPOINT_IDENTIFICATION_ALGORITHM_CONFIG));
        Assert.assertEquals("com.example.MySslEngineFactory", props.get(SslConfigs.SSL_ENGINE_FACTORY_CLASS_CONFIG));
        Assert.assertEquals("SunX509", props.get(SslConfigs.SSL_KEYMANAGER_ALGORITHM_CONFIG));
        Assert.assertEquals("SHA1PRNG", props.get(SslConfigs.SSL_SECURE_RANDOM_IMPLEMENTATION_CONFIG));
        Assert.assertEquals("PKIX", props.get(SslConfigs.SSL_TRUSTMANAGER_ALGORITHM_CONFIG));
    }
}
