DROP TABLE UsersAuthorities
DROP TABLE Authorities
DROP TABLE Users
DROP TABLE PointToPointFlow
DROP TABLE PointToPointFlowProfile
DROP TABLE Module
DROP TABLE StartupControl
DROP TABLE SystemEvent
DROP TABLE ConfParamString
DROP TABLE ConfParamMapString
DROP TABLE ConfParamMap
DROP TABLE ConfParamLong
DROP TABLE ConfParamListString
DROP TABLE ConfParamList
DROP TABLE ConfParamInteger
DROP TABLE ConfParamBoolean
DROP TABLE ConfigurationParameter
DROP TABLE Configuration
DROP TABLE FlowEventTriggerParameters
DROP TABLE FlowEventTrigger
DROP TABLE Version
DROP TABLE ExclusionEvent
DROP TABLE MessageFilter
DROP TABLE IkasanWiretap
DROP TABLE RolePolicy
DROP TABLE PrincipalRole
DROP TABLE SecurityRole
DROP TABLE SecurityPolicy
DROP TABLE SecurityPrincipal
DROP TABLE MCSKeyLocationQuery
DROP TABLE MCSMappingConfiguration
DROP TABLE MCSConfigurationContext
DROP TABLE MCSConfigurationType			
DROP TABLE MCSSourceConfigGroupSeq
DROP TABLE MCSSourceConfigValue
DROP TABLE MCSTargetConfigValue
DROP TABLE MCSConfigServiceClient
DROP TABLE AuthenticationMethod
DROP TABLE PolicyLinkType
DROP TABLE PolicyLink
DROP TABLE UserPrincipal
DROP TABLE SecurityPrincipal
DROP TABLE Users